document.write('<nav class="navbar navbar-expand-lg navbar-dark bg-dark" style = "position:fixed; top:0; right:0; left:0; z-index:1030;">')
document.write('      <div class="container-fluid">')
document.write('        <a class="navbar-brand px-5-md"  href="#">HARC</a>')
document.write('        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">')
document.write('          <span class="navbar-toggler-icon"></span>')
document.write('        </button>')
document.write('        <div class="collapse navbar-collapse" id="navbarSupportedContent">')
document.write('          <ul class="navbar-nav me-auto mb-2 mb-lg-0">')
document.write('            <li class="nav-item">')
document.write('              <a class="nav-link" href="index.html">Welcome</a>')
document.write('            </li>')
document.write('            <li class="nav-item dropdown">')
document.write('              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">')
document.write('                Club Information')
document.write('              </a>')
document.write('              <ul class="dropdown-menu">')
document.write('                <li><a class="dropdown-item" href="public_service.html">Public Service</a></li>')
document.write('                <li><a class="dropdown-item" href="calendar.html">Events/Calendar</a></li>')
document.write('                <li><a class="dropdown-item" href="club_officers.html">Officers</a></li>')
document.write('                <li><a class="dropdown-item" href="silent_key_members.html">Silent Keys</a></li>')
document.write('                <li><hr class="dropdown-divider bg-dark"></li>')
document.write('                <li><a class="dropdown-item" href="apply_for_membership.html">Join</a></li>')
document.write('                <li><a class="dropdown-item" href="donate.html">Donate</a></li>')
document.write('              </ul>')
document.write('            </li>')
document.write('            <li class="nav-item dropdown">')
document.write('              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">')
document.write('                Local Airwaves')
document.write('              </a>')
document.write('              <ul class="dropdown-menu">')
document.write('                <li><a class="dropdown-item" href="local_repeaters.html">Repeaters</a></li>')
document.write('                <li><a class="dropdown-item" href="local_nets.html">Nets</a></li>')
document.write('                <li><a class="dropdown-item" href="scanner_freqs.html">Scanner Freqs</a></li>')
document.write('                <li><hr class="dropdown-divider bg-dark"></li>')
document.write('                <li><a class="dropdown-item" href="wpaSimplexMap.html">WPA District Simplex Map</a></li>')
document.write('              </ul>')
document.write('            </li>')
document.write('            <li class="nav-item dropdown">')
document.write('              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">')
document.write('                HAM Radio Info')
document.write('              </a>')
document.write('              <ul class="dropdown-menu">')
document.write('                <li><a class="dropdown-item" href="information_for_beginners.html">Information for Beginners</a></li>')
document.write('                <li><a class="dropdown-item" href="exams.html">Exam Sessions</a></li>')
document.write('                <li><a class="dropdown-item" href="organizations.html">Organizations</a></li>')
document.write('                <li><hr class="dropdown-divider bg-dark"></li>')
document.write('                <li><a class="dropdown-item" href="amateur_radio_links.html">Misc Links</a></li>')
document.write('              </ul>')
document.write('            </li>')
document.write('          </ul>')
document.write('<!--            <form class="d-flex" role="search">')
document.write('            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">')
document.write('            <button class="btn btn-outline-success" type="submit">Search</button>')
document.write('          </form>')
document.write('        -->')
document.write('        </div>')
document.write('      </div>')
document.write('    </nav>')
document.write('    <hr>')
document.write('    <p style="margin-top: 10px;">&nbsp;</p>')